### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by Guaderxx** [0x3alex/GoSnake#1]
Arch: x86_64    
GoVersion: 1.19.2

I can't run after I executed the `apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev`.    

Is there something I should do while `go build`

**Comment by 0x3alex** [comment]
Tuff one...
I assume there is some error regarind the `SDL.h `header?

**Comment by Guaderxx** [comment]
Actually, I can open a window with *Go, Snake Score: 0* at top.   
But it closed quickly, even cant read the top words.

**Comment by Guaderxx** [comment]
I want to make a suggestion, you should handle error when it created, 
rather than ignore it

**Comment by 0x3alex** [comment]
I am handling it, because I exit on the error

**Comment by 0x3alex** [comment]
Alright. I pushed an update, where it just panics on an error. Would you mind sharing the output?

**Comment by Guaderxx** [comment]
Actually, the same like before, just quit like normal with no log or something else.
I think I have to check the `go-sdl2` examples

**Comment by 0x3alex** [comment]
Oh yeah, I forogt that. It seems like, that the functions might think you already hit something...which is really weird.

I now setup go and sdl2 on my windows 11 install and it just works fine...

**Comment by Guaderxx** [comment]
It's weird because I have to run it with `sdl.Do()`, otherwise it cannt work

It seems to be a OS problem, forget it

**Comment by 0x3alex** [comment]
Weird... Mind sharing exactly what you changed?
